# Generated by Django 4.2.6 on 2023-11-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_remove_branch_working_employees'),
        ('users', '0011_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='branches.branch'),
        ),
    ]
