# Generated by Django 4.2.6 on 2023-11-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
    ]
