# Generated by Django 4.2.7 on 2023-11-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0006_alter_branch_working_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_area', models.PositiveIntegerField(default=0)),
                ('shared_area', models.PositiveIntegerField(default=0)),
                ('meeting_rooms', models.PositiveIntegerField(default=0)),
                ('branch_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roomsBranch_id', to='branches.branch')),
            ],
        ),
    ]
