# Generated by Django 4.2.7 on 2023-11-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_remove_branch_working_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('shared', 'Shared Room'), ('quiet', 'Quiet Room'), ('meeting', 'Meeting Room')], max_length=20)),
                ('branch_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roomssBranch_id', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
