# Generated by Django 4.2.6 on 2023-10-23 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
