# Generated by Django 4.2.7 on 2023-11-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='offer',
        ),
    ]
