# Generated by Django 4.2.7 on 2023-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
