# Generated by Django 4.2.6 on 2023-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_created_at_package_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
