# Generated by Django 4.2.6 on 2023-10-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('manager_name', models.CharField(blank=True, max_length=50)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
