# Generated by Django 4.2.6 on 2023-10-25 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid name.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
