# Generated by Django 4.2.6 on 2023-11-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
        ('branches', '0002_remove_branch_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='employee_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
