# Generated by Django 4.2.6 on 2023-10-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_name'),
        ('branches', '0002_remove_branch_established_date_branch_created_at_and_more'),
    ]

    operations = [
    ]
