# Generated by Django 4.2.6 on 2023-11-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_merge_20231025_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
