# Generated by Django 4.2.7 on 2023-11-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_delete_branch'),
        ('branches', '0004_remove_branch_employee_id_workingin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='kitchen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen'),
        ),
    ]
