# Generated by Django 4.2.6 on 2023-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_address_alter_user_national_id_and_more'),
        ('branches', '0004_remove_branch_employee_id_workingin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='working_employees',
            field=models.ManyToManyField(related_name='working_employees', to='users.user'),
        ),
        migrations.DeleteModel(
            name='WorkingIN',
        ),
    ]
