# Generated by Django 4.2.6 on 2023-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_address_alter_user_national_id_and_more'),
        ('branches', '0005_branch_working_employees_delete_workingin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='working_employees',
            field=models.ManyToManyField(blank=True, related_name='working_employees', to='users.user'),
        ),
    ]
