# Generated by Django 4.2.7 on 2023-11-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_branch_employee_id'),
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='users.user')),
                ('employee_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='users.user')),
            ],
        ),
    ]
