# Generated by Django 4.2.6 on 2023-11-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_working_employees'),
        ('users', '0010_alter_user_address_alter_user_national_id_and_more'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='checkin_time',
            new_name='check_in_time',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='checkout_time',
            new_name='check_out_time',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='price',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='history',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_id', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='history',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='users.user'),
        ),
        migrations.AlterField(
            model_name='history',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='users.user'),
        ),
    ]
