# Generated by Django 4.2.7 on 2023-11-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_employee_id'),
        ('users', '0009_alter_user_email'),
        ('history', '0002_alter_history_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='branch_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='history',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='users.user'),
        ),
    ]
