# Generated by Django 4.2.6 on 2023-11-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0002_rename_checkin_time_history_check_in_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='history',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_id', to='users.user'),
        ),
    ]
