# Generated by Django 4.2.6 on 2023-11-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0003_rename_branch_id_history_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_id', to='users.user'),
        ),
    ]
