# Generated by Django 4.2.6 on 2023-11-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_remove_branch_working_employees'),
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0004_alter_history_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='history',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.user'),
        ),
        migrations.AlterField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee', to='users.user'),
        ),
    ]
