# Generated by Django 4.2.6 on 2023-11-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0005_alter_history_branch_alter_history_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='users.user'),
        ),
    ]
