# Generated by Django 4.2.6 on 2023-11-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0006_alter_history_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='users.user'),
        ),
    ]
