# Generated by Django 4.2.6 on 2023-11-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_history_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='employee',
        ),
    ]
