# Generated by Django 4.2.6 on 2023-11-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_remove_history_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='history',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='client',
        ),
    ]
