# Generated by Django 4.2.6 on 2023-11-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_remove_history_branch_remove_history_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='payment',
        ),
    ]
