# Generated by Django 4.2.6 on 2023-11-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0010_remove_history_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
    ]
