# Generated by Django 4.2.6 on 2023-11-12 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_remove_branch_working_employees'),
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0011_history_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='client',
        ),
        migrations.AddField(
            model_name='history',
            name='branch_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='branch_id', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='history',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='client_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client_id', to='users.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='employee_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_id', to='users.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
