# Generated by Django 4.2.6 on 2023-11-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_remove_branch_working_employees'),
        ('users', '0014_alter_user_branch_alter_user_created_by'),
        ('history', '0012_remove_history_client_history_branch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='history',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='branch', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='history',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client', to='users.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee', to='users.user'),
        ),
    ]
