# Generated by Django 4.2.6 on 2023-10-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kitchen',
        ),
    ]
