# Generated by Django 4.2.7 on 2023-11-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_branch_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
