# Generated by Django 3.2.10 on 2023-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='entity_name',
            field=models.CharField(max_length=255),
        ),
    ]
