# Generated by Django 4.2.7 on 2023-11-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_working_employees'),
        ('products', '0002_alter_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='branch_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productsBranch_id', to='branches.branch'),
        ),
    ]
